/*
This source code is part of the Thoyik
Copyright (C) 2013  Yoserizal
Feedback / Bug Reports yoser174@gmail.com


This project used:
KFRAMEWORK  (http://k-framework.sourceforge.net/)
 */

package KFramework30.Printing;

// ale utils
import KFramework30.Base.*;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;


//rtl
import javax.swing.event.*;
import javax.swing.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class jasperPrinting 
extends javax.swing.JDialog 
implements ListSelectionListener{

    //uses
    private KConfigurationClass  configuration;
    private KLogClass            log;

    // has - defaulted
    private selectFieldActionListenerClass  selectFieldActionListener;
    private summaryActionListenerClass      summaryActionListener;

    private boolean                OKCloseFlag;

/** Creates new form printSettingClass */
    public jasperPrinting( KConfigurationClass configurationParam, 
                                    KLogClass logParam,   
                                    java.awt.Window parentWindow,
                                    KPrintDataTableClass DBPrinterParam,Integer hdrID,File file ) 
    throws KExceptionClass
    {
            
        super( parentWindow, java.awt.Dialog.ModalityType.DOCUMENT_MODAL );   
        
        initComponents ();
        pack ();  
        // width, height, position
        setSize( 477, 380 );
        setTitle("Print Setting");
        KMetaUtilsClass.centerInScreen( this );	
        
        //uses
	configuration = configurationParam;
	log = logParam;                                            
         
        // has - defaulted
        OKCloseFlag = false;
    
      
        try 
        {
            Map<String, Object> parameters = new HashMap<String, Object>();
            parameters.put("PRId", hdrID);
            closeDialog(null);
            //Class.forName("oracle.jdbc.OracleDriver") ;
       
            JasperDesign jasperDesign = JRXmlLoader.load(file);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            Connection jdbcConnection = DriverManager.getConnection(configuration.getField( "jasper_jdbc" ), "sample", "sample");
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameters,jdbcConnection);
            JasperViewer.viewReport(jasperPrint,false);
            this.setModal(true);
            }
         catch( Exception error	){
            log.log( this, KMetaUtilsClass.getStackTrace( error ) );
            KMetaUtilsClass.showErrorMessageFromException( this, error );
        }			                    
    }

     
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 433, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
    
    /** Process for lists selectoin change */
    public void valueChanged(javax.swing.event.ListSelectionEvent evt) {

        //enable and disable components

    }
   
    
    public boolean dialogCloseResult( )
    {
        show();       
        
        return OKCloseFlag;
    }    
}
